sudo: required
services:
  - docker

scripts:
  - docker build -t lorebianchi/node .
  - docker images lorebianchi/node 

before_deploy:
  - docker login -u $docker_username -p $docker_password

deploy:
  provider: script
  script: docker push lorebianchi/node
  on:
    branch: master